### ISSUE TITLE
Cache embeds client-side

### ISSUE THREAD

**Issue by xyaahu** [BobaBoard/issues#4]
## What's your request?
**Is it related to a problem?**
Embeds do not change as often as they're being reloaded. 

**Describe the solution you'd like**
Explore how to cache them client-side.

## Anything else?
Ticket migrated from [the task dump](https://docs.google.com/document/d/1zwjZKZh2lxlfHXoHPCEfsHQdvx97Te9eqCBtouLOpsw/edit#) on behalf of The Webmaster.

**Comment by essential-randomness** [comment]
This got done at some point!
