### ISSUE TITLE
Clean up menu actions implementation

### ISSUE THREAD

**Issue by xyaahu** [BobaBoard/issues#6]
## What's your request?
**Is it related to a problem?**
The same menu actions can occur in different places, but currently it isn't simple to do that without copying code.

**Suggested actions?**
Unify how menu actions are added in various places so options can be easily repeated in different views (e.g. edit tags should be possible from both within thread and from board view and it shouldn't require duplicating code.

## Anything else?
Ticket migrated from [the task dump](https://docs.google.com/document/d/1zwjZKZh2lxlfHXoHPCEfsHQdvx97Te9eqCBtouLOpsw/edit#) on behalf of The Webmaster.

**Comment by essential-randomness** [comment]
Been working on this!

**Comment by essential-randomness** [comment]
Done in these two commits: 
[post options]: https://github.com/essential-randomness/boba-frontend/commit/ee85124244e846a18e227b537b3a29a904da49a0
[board options]: https://github.com/essential-randomness/boba-frontend/commit/19cae17439ab898100b14b9d6bc8afc6a6fc382d
